### PR TITLE
Fix login. Details below.

### PR DESCRIPTION
**Pull request by emcmanus**
The second `upcase!` call in `include?()` will return nil, since no
changes were made to the string. Docs:
http://ruby-doc.org/core-2.2.3/String.html#method-i-upcase

### CODE REVIEW

**Comment by xssc** [comment]
Wow, can't believe I missed that, my bad.

**Comment by emcmanus** [comment]
No worries, thanks for the library!

**Comment by xssc** [comment]
it's @nabeelamjad's library

**Comment by emcmanus** [comment]
(Thanks, @nabeelamjad!)

**Comment by nabeelamjad** [comment]
Thanks, can't believe I didn't properly read over the code either. I was initially thinking of adding tests (using RSpec) but since Niantec is most likely going to impede the API at some point I doubt it's worth it.

**Pull request merged**
