### PR TITLE
Add S2 Geometry classes to Poke-API

### LINKED ISSUE #2: Obtaining cell_ids
Hello, can you say how did you generated cell_id in the exmaple.rb ? And what cell_id we need?

### PR DESCRIPTION
**Pull request by nabeelamjad**
If anyone can have a double check over this before I merge it in then that'd be greatly appreciated!

This fixes #2

### CODE REVIEW

**Comment by xssc** [comment]
Not a lot of ruby devs on the discord so throwing it out there that I can check this over tomorrow (btw Id consider making this its own gem, even thought it not full s2(neither is s2phere) but not required).

**Comment by nabeelamjad** [comment]
Yeah could do that I suppose, though it will lack a lot of functionality in general for anyone wanting to use it outside the scope of Pokemon GO (which is why I added it in the the gem itself).

**Comment by xssc** [comment]
Well maybe if theres a wider demand people would be more likely to contribute outside of pogo. Just a thought. Call it an unfinished port or something

**Comment by nabeelamjad** [comment]
Sounds good, I'll create its own repository tomorrow.

**Pull request closed without merging**
