### PR TITLE
add google login

### PR DESCRIPTION
**Pull request by xssc**
I was attempting to create a ruby port of the API (but failed) but manages to port over gpsoauth in the proccess (https://github.com/xssc/gpsoauth). I built and tested this on my local machine and it works great.

### CODE REVIEW

**Comment by coalwater** [comment]
@xssc I downloaded your branch and tested it on my account, I confirm that it's working fine without any problems :+1:

**Comment by nabeelamjad** [comment]
Thanks @xssc, does this work for non-browser based machines as well? (I'm not able to test it until evening).

**Comment by xssc** [comment]
@nabeelamjab yup

**Comment by nabeelamjad** [comment]
@xssc - confirmed working, I'll merge it in. 

I might do some refactor work at some point (to keep it consistent with Ruby style guide) as well as update the Readme. I'll release a new tag tomorrow as well for the addition of Google login.

Thanks again!

**Comment by xssc** [comment]
@nabeelamjad okay, and oops, I accidentally yanked v0.1.0(first gem, thought I could push the same version so it didnt need to be updated), so poke-api.gempsec needs to updated to require v0.1.1, I updated the gem so it doesn't require libcurl (can be a hassle to install on windows).  sorry, I'm still learning. Nothing else needs to be changed though.

**Comment by nabeelamjad** [comment]
Alright will do.

**Comment by nabeelamjad** [comment]
@xssc - updated and pushed as 0.0.2, thanks once again!

**Pull request merged**
